=== jgazeau/bmyc/bmyc/bmyc.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "BMYC Configuration File Schema",
  "description": "Schema for the .bmycconfig.json file.",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "package": {
        "type": "string"
      },
      "hold": {
        "type": "boolean",
        "default": false
      },
      "name": {
        "type": "string"
      },
      "localPath": {
        "type": "string"
      },
      "currentVersion": {
        "type": "string"
      },
      "assetManager": {
        "type": "object",
        "oneOf": [
          {
            "properties": {
              "name": {
                "const": "cdnjs"
              },
              "library": {
                "type": "string"
              },
              "fileName": {
                "type": "string"
              }
            },
            "required": ["name", "library", "fileName"]
          },
          {
            "properties": {
              "name": {
                "const": "github"
              },
              "owner": {
                "type": "string"
              },
              "repository": {
                "type": "string"
              },
              "filePath": {
                "type": "string"
              }
            },
            "required": ["name", "owner", "repository", "filePath"]
          },
          {
            "properties": {
              "name": {
                "const": "unpkg"
              },
              "library": {
                "type": "string"
              },
              "filePath": {
                "type": "string"
              }
            },
            "required": ["name", "library", "filePath"]
          },
          {
            "properties": {
              "name": {
                "const": "jsdelivr"
              },
              "cdn": {
                "type": "string"
              },
              "package": {
                "type": "string"
              },
              "filePath": {
                "type": "string"
              }
            },
            "required": ["name", "cdn", "package", "filePath"]
          }
        ]
      }
    },
    "required": ["package", "name", "localPath", "assetManager"]
  }
}

=== jgazeau/bmyc/test/resources/config-ok.json
[
  {
    "package": "package1",
    "name": "asset1",
    "hold": false,
    "localPath": "path/asset1.min.js",
    "assetManager": {
      "name": "cdnjs",
      "library": "library",
      "fileName": "asset1.min.js"
    },
    "currentVersion": "0.0.1"
  },
  {
    "package": "package2",
    "name": "asset2",
    "hold": false,
    "localPath": "./path/asset2.min.js",
    "assetManager": {
      "name": "github",
      "owner": "owner",
      "repository": "repository",
      "filePath": "dir/asset2.min.js"
    }
  },
  {
    "package": "package3",
    "name": "asset3",
    "hold": false,
    "localPath": "./path/asset3.min.js",
    "assetManager": {
      "name": "unpkg",
      "library": "asset3",
      "filePath": "dist/asset3.min.js"
    }
  },
  {
    "package": "package4",
    "name": "asset4",
    "hold": false,
    "localPath": "./path/asset4.min.js",
    "assetManager": {
      "name": "jsdelivr",
      "cdn": "npm",
      "package": "asset4",
      "filePath": "dist/asset4.min.js"
    }
  }
]
